package prueba3;

import java.util.Random;

public class Ejercicio07 {
    public static void main(String[] args) {
        Random ran = new Random();
        int primero = ran.nextInt(100) + 1;
        int segundo = ran.nextInt(100) + 1;
        System.out.println("valor de primero: " + primero);
        System.out.println("valor de segundo: " + segundo);
        System.out.println("primero < segundo: " + (primero < segundo));
        System.out.println("primero > segundo: " + (primero > segundo));
        System.out.println("primero == segundo: " + (primero == segundo));
        System.out.println("primero >= segundo: " + (primero >= segundo));
        System.out.println("primero <= segundo: " + (primero <= segundo));
        System.out.println("primero != segundo: " + (primero != segundo));
        System.out.println("(primero < 10) && (segundo < 10): " + ((primero < 10) && (segundo < 10)));
        System.out.println("(primero > 10) && (segundo > 10): " + ((primero > 10) && (segundo > 10)));
        System.out.println("(primero < 10) || (segundo < 10): " + ((primero < 10) || (segundo < 10)));
        System.out.println("(primero > 10) || (segundo > 10): " + ((primero > 10) || (segundo > 10)));
        System.out.println("OTRO EJERCICIO -------------------------------");
        int i = -1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 10;
        System.out.println(Integer.toBinaryString(i));
        i >>= 5;
        System.out.println(Integer.toBinaryString(i));
        i <<= 5;
        System.out.println(Integer.toBinaryString(i));
        i <<= 20;
        System.out.println("i << 20" + Integer.toBinaryString(i));
        i = 1;
        System.out.println("1: " + Integer.toBinaryString(i));
        i = 2;
        System.out.println("2: " + Integer.toBinaryString(i));
        i = 3;
        System.out.println("3: " + Integer.toBinaryString(i));
        i = 4;
        System.out.println("4: " + Integer.toBinaryString(i));
        i = 5;
        System.out.println("5: " + Integer.toBinaryString(i));
        i = 6;
        System.out.println("6: " + Integer.toBinaryString(i));
        i = 7;
        System.out.println("7: " + Integer.toBinaryString(i));
        i = 8;
        System.out.println("8: " + Integer.toBinaryString(i));
        i = 9;
        System.out.println("9: " + Integer.toBinaryString(i));
        i = 10;
        System.out.println("10: " + Integer.toBinaryString(i));
        i = 11;
        System.out.println("11: " + Integer.toBinaryString(i));
        i = 12;
        System.out.println("12: " + Integer.toBinaryString(i));
        i = 13;
        System.out.println("13: " + Integer.toBinaryString(i));
        i = 14;
        System.out.println("14: " + Integer.toBinaryString(i));
        i = 15;
        System.out.println("15: " + Integer.toBinaryString(i));
        byte bi = -1;
        System.out.println(Integer.toBinaryString(bi));
        bi >>>= 10;
        System.out.println(Integer.toBinaryString(bi));
        bi >>= 5;
        System.out.println(Integer.toBinaryString(bi));
        bi <<= 5;
        System.out.println(Integer.toBinaryString(bi));
        bi <<= 20;
        System.out.println("OTRO EJERCICIO -------------------------------");

        System.out.println("i << 20: " + Integer.toBinaryString(bi));
        bi = 1;
        System.out.println(Integer.toBinaryString(bi));
        bi = 2;
        System.out.println("2: " + Integer.toBinaryString(bi));
        bi = 3;
        System.out.println("3: " + Integer.toBinaryString(bi));
        bi = 4;
        System.out.println("4: " + Integer.toBinaryString(bi));
        bi = 5;
        System.out.println("5: " + Integer.toBinaryString(bi));
        bi = 6;
        System.out.println("6: " + Integer.toBinaryString(bi));
        bi = 7;
        System.out.println("7: " + Integer.toBinaryString(bi));
        bi = 8;
        System.out.println("8: " + Integer.toBinaryString(bi));
        bi = 9;
        System.out.println("9: " + Integer.toBinaryString(bi));
        bi = 10;
        System.out.println("10: " + Integer.toBinaryString(bi));
        bi = 11;
        System.out.println("11: " + Integer.toBinaryString(bi));
        bi = 12;
        System.out.println("12: " + Integer.toBinaryString(bi));
        bi = 13;
        System.out.println("13: " + Integer.toBinaryString(bi));
        bi = 14;
        System.out.println("14: " + Integer.toBinaryString(bi));
        bi = 15;
        System.out.println("15: " + Integer.toBinaryString(bi));

//        Short s = -1;
//        System.out.println(Integer.toBinaryString(s));
//        s >>>= 10;
//        System.out.println(Integer.toBinaryString(s));
//        s <<= 5;
//        System.out.println(Integer.toBinaryString(s));
        System.out.println("con long: ");
        long l = -2;
        System.out.println(Long.toBinaryString(l));
        l <<= 10;
        System.out.println(Long.toBinaryString(l));
        l >>>= 5;
        System.out.println(Long.toBinaryString(l));
        l >>= 5;
        System.out.println(Long.toBinaryString(l));
        System.out.println("con byte: ");
        byte b = -1;
        System.out.println(Integer.toBinaryString(b));
        b >>>= 10;
        System.out.println(Integer.toBinaryString(b));
        b = -1;
        System.out.println(Integer.toBinaryString(b >>> 10));
        int x = 10;
        int y = 15;
        int result = 1;
        result = x < y ? result * 10 : result * 100;
        System.out.println("y el resultado es: " + result);
        double mira = 1.9;
        float tu = 1.4f;
        System.out.println("y el resultado es: " + (double)x);
        System.out.println("y el resultado es: " + (int)mira);
        System.out.println("y el resultado es: " + (int)tu);
        System.out.println("y el resultado es: " + (int)Math.round(tu));
        result = x ^ y;
        System.out.println("y el resultado es: " + result);
        mira = +tu;
        System.out.println("y el resultado es: " + mira);
        mira = -tu;
        System.out.println("y el resultado es: " + mira);
        int big = Integer.MAX_VALUE;
        //el int mas grande
        System.out.println("y el resultado es: " + big);
        int biger = big * 4;
        //si lo multiplicas por 4 da -4
        //pero si lo multiplicas por 5 o mas le resta uno menos del numero que has puesto
        System.out.println("y el resultado es: " + biger);

    }
}
